# Generated by Django 4.1.1 on 2022-09-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nServicio', models.CharField(max_length=50)),
                ('tiempo', models.IntegerField(max_length=3)),
                ('precio', models.FloatField(max_length=6)),
            ],
        ),
    ]
