# Generated by Django 4.1.1 on 2022-09-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='tiempo',
            field=models.IntegerField(),
        ),
    ]
